// Pure system id → display name + emoji map. No server-only imports, so it can be
// used from both server code (lib/recalbox/systems.ts, the icon proxy) and client
// components (now-playing emoji fallback).

export type SystemMeta = { name: string; emoji: string }

export const SYSTEM_META: Record<string, SystemMeta> = {
	'3do': { name: '3DO', emoji: '🎮' },
	'64dd': { name: 'N64 Disk Drive', emoji: '💾' },
	amiga1200: { name: 'Amiga 1200', emoji: '🖥️' },
	amiga600: { name: 'Amiga 600', emoji: '🖥️' },
	amigacd32: { name: 'Amiga CD32', emoji: '💿' },
	amigacdtv: { name: 'Amiga CDTV', emoji: '📺' },
	amstradcpc: { name: 'Amstrad CPC', emoji: '🖥️' },
	apple2: { name: 'Apple II', emoji: '🍎' },
	apple2gs: { name: 'Apple IIGS', emoji: '🍎' },
	arduboy: { name: 'Arduboy', emoji: '🕹️' },
	atari2600: { name: 'Atari 2600', emoji: '🕹️' },
	atari5200: { name: 'Atari 5200', emoji: '🕹️' },
	atari7800: { name: 'Atari 7800', emoji: '🕹️' },
	atari800: { name: 'Atari 800', emoji: '🕹️' },
	atarist: { name: 'Atari ST', emoji: '🖥️' },
	atomiswave: { name: 'Atomiswave', emoji: '🕹️' },
	c64: { name: 'Commodore 64', emoji: '🖥️' },
	cdi: { name: 'CD-i', emoji: '💿' },
	channelf: { name: 'Channel F', emoji: '🕹️' },
	colecovision: { name: 'ColecoVision', emoji: '🕹️' },
	dreamcast: { name: 'Dreamcast', emoji: '🌀' },
	fbneo: { name: 'FinalBurn Neo', emoji: '👾' },
	fds: { name: 'Famicom Disk System', emoji: '💾' },
	gamecube: { name: 'GameCube', emoji: '🟣' },
	gamegear: { name: 'Game Gear', emoji: '🎮' },
	gb: { name: 'Game Boy', emoji: '🟩' },
	gba: { name: 'Game Boy Advance', emoji: '🟦' },
	gbc: { name: 'Game Boy Color', emoji: '🌈' },
	gw: { name: 'Game & Watch', emoji: '⌚' },
	gx4000: { name: 'GX4000', emoji: '🕹️' },
	intellivision: { name: 'Intellivision', emoji: '🕹️' },
	jaguar: { name: 'Atari Jaguar', emoji: '🐆' },
	lutro: { name: 'Lutro', emoji: '🕹️' },
	lynx: { name: 'Atari Lynx', emoji: '🎮' },
	mame: { name: 'MAME', emoji: '👾' },
	mastersystem: { name: 'Master System', emoji: '⚫' },
	megadrive: { name: 'Mega Drive', emoji: '🔵' },
	megaduck: { name: 'Mega Duck', emoji: '🦆' },
	model3: { name: 'Model 3', emoji: '🕹️' },
	msx1: { name: 'MSX', emoji: '🖥️' },
	msx2: { name: 'MSX2', emoji: '🖥️' },
	multivision: { name: 'Multivision', emoji: '🕹️' },
	n64: { name: 'Nintendo 64', emoji: '🔴' },
	naomi: { name: 'Naomi', emoji: '🕹️' },
	naomi2: { name: 'Naomi 2', emoji: '🕹️' },
	naomigd: { name: 'Naomi GD-ROM', emoji: '💿' },
	nds: { name: 'Nintendo DS', emoji: '📱' },
	neogeo: { name: 'Neo Geo', emoji: '🔴' },
	neogeocd: { name: 'Neo Geo CD', emoji: '💿' },
	nes: { name: 'NES', emoji: '🍄' },
	ngp: { name: 'Neo Geo Pocket', emoji: '🎮' },
	ngpc: { name: 'Neo Geo Pocket Color', emoji: '🌈' },
	o2em: { name: 'Odyssey²', emoji: '🕹️' },
	oricatmos: { name: 'Oric-Atmos', emoji: '🖥️' },
	pcengine: { name: 'PC Engine', emoji: '⚪' },
	pcenginecd: { name: 'PC Engine CD', emoji: '💿' },
	pcfx: { name: 'PC-FX', emoji: '🎮' },
	pico: { name: 'Pico-8', emoji: '🎮' },
	pokemini: { name: 'Pokémon Mini', emoji: '🟡' },
	psp: { name: 'PSP', emoji: '📺' },
	psx: { name: 'PlayStation', emoji: '🔲' },
	satellaview: { name: 'Satellaview', emoji: '📡' },
	saturn: { name: 'Saturn', emoji: '🪐' },
	scummvm: { name: 'ScummVM', emoji: '🖱️' },
	sega32x: { name: 'Sega 32X', emoji: '🔴' },
	segacd: { name: 'Sega CD', emoji: '💿' },
	sg1000: { name: 'SG-1000', emoji: '🕹️' },
	snes: { name: 'Super Nintendo', emoji: '🟣' },
	supervision: { name: 'Supervision', emoji: '🎮' },
	vectrex: { name: 'Vectrex', emoji: '🕹️' },
	vic20: { name: 'VIC-20', emoji: '🖥️' },
	virtualboy: { name: 'Virtual Boy', emoji: '🔴' },
	wii: { name: 'Wii', emoji: '🎯' },
	wswan: { name: 'WonderSwan', emoji: '🎮' },
	wswanc: { name: 'WonderSwan Color', emoji: '🌈' },
	x68000: { name: 'X68000', emoji: '🖥️' },
	zx81: { name: 'ZX81', emoji: '🖥️' },
	zxspectrum: { name: 'ZX Spectrum', emoji: '🌈' },
}

export function systemMeta(id: string): SystemMeta {
	return SYSTEM_META[id] ?? { name: id.toUpperCase(), emoji: '🎮' }
}

export function systemEmoji(id: string): string {
	return systemMeta(id).emoji
}
