// FR → EN mapping built from Screenscraper API (genresListe) + DB genre tokens
export const GENRE_FR_TO_EN: Record<string, string> = {
	Action: 'Action',
	'Action / Aventure': 'Action / Adventure',
	'Action / Casse briques': 'Action / Breakout games',
	'Action / Escalade': 'Action / Climbing',
	'Action / Labyrinthe': 'Action / Labyrinth',
	'Action RPG': 'Action RPG',
	'Action-Aventure': 'Action / Adventure',
	'Action-Combat': 'Action / Combat',
	'Action-Flipper': 'Action / Pinball',
	'Action-Jeu de rôles': 'Action / RPG',
	'Action-Plateforme': 'Action / Platform',
	"Action-Shoot'em Up": "Action / Shoot'em Up",
	Adulte: 'Adults',
	'Adulte-Aventure': 'Adults / Adventure',
	Aventure: 'Adventure',
	'Aventure / 3D Temps Réel': 'Adventure / Real-Time 3D',
	'Aventure / Film Interactif': 'Adventure / Interactive Movie',
	'Aventure / Graphique': 'Adventure / Graphic',
	'Aventure / Point and Click': 'Adventure / Point and Click',
	'Aventure / Roman Visuel': 'Adventure / Visual Novel',
	'Aventure / Survival Horror': 'Adventure / Survival Horror',
	'Aventure / Texte': 'Adventure / Text',
	"Beat'em All": "Beat'em Up",
	Casino: 'Casino',
	'Casino / Cartes': 'Casino / Cards',
	'Casino / Course': 'Casino / Race',
	'Casino / Loterie': 'Casino / Lottery',
	'Casino / Machine a sous': 'Casino / Slot Machine',
	'Casino / Roulette': 'Casino / Roulette',
	'Casual Game': 'Casual Game',
	Chant: 'Singing',
	Chasse: 'Hunting',
	'Chasse et Peche': 'Hunting and Fishing',
	Combat: 'Fighting',
	'Combat / 2.5D': 'Fighting / 2.5D',
	'Combat / 2D': 'Fighting / 2D',
	'Combat / 3D': 'Fighting / 3D',
	'Combat / Versus': 'Fighting / Versus',
	'Combat / Versus Co-op': 'Fighting / Vs Co-op',
	'Combat / Vertical': 'Fighting / Vertical',
	Compilation: 'Compilation',
	Conduite: 'Driving',
	'Conduite / Avion': 'Driving / Plane',
	'Conduite / Bateau': 'Driving / Boat',
	'Conduite / Course': 'Driving / Racing',
	'Conduite / Deltaplane': 'Driving / Hang Gliding',
	'Conduite / Moto': 'Driving / Motorcycle',
	'Construction & Management': 'Build and Management',
	Course: 'Racing',
	'Course de chevaux': 'Horse Racing',
	'Course de Moto vue 1er pers.': 'Motorcycle Race FPV',
	'Course de Moto vue 3eme pers.': 'Motorcycle Race TPV',
	'Course vue 1ere pers.': 'Racing FPV',
	'Course vue 3eme pers.': 'Racing TPV',
	'Course, Conduite': 'Racing, Driving',
	'Course, Conduite / Avion': 'Racing, Driving / Plane',
	'Course, Conduite / Bateau': 'Racing, Driving / Boat',
	'Course, Conduite / Course': 'Racing, Driving / Racing',
	'Course, Conduite / Deltaplane': 'Racing, Driving / Hang Gliding',
	'Course, Conduite / Moto': 'Racing, Driving / Motorcycle',
	Danse: 'Dancing',
	Demo: 'Demo',
	Diagonal: 'Diagonal',
	Divers: 'Various',
	'Divers / Electro-mecanique': 'Various / Electro-Mechanical',
	'Divers / Print Club': 'Various / Print Club',
	'Divers / Système': 'Various / System',
	'Divers / Utilitaires': 'Various / Utilities',
	'Dungeon RPG': 'Dungeon Crawler RPG',
	Flipper: 'Pinball',
	Go: 'Go',
	Hanafuda: 'Hanafuda',
	Horizontal: 'Horizontal',
	'Jeu de cartes': 'Playing Cards',
	'Jeu de Rôle Japonais': 'Japanese RPG',
	'Jeu de Rôle Tactique': 'Tactical RPG',
	'Jeu de rôles': 'Role Playing Game',
	'Jeu de rôles en équipe': 'Party-Based RPG',
	'Jeu de societe / plateau': 'Board Game',
	'Jeu de societe asiatique': 'Asiatic Board Game',
	'Ludo-Educatif': 'Educational',
	Mahjong: 'Mahjong',
	MMORPG: 'MMORPG',
	Musique: 'Music',
	'Musique et Danse': 'Music and Dancing',
	'N/A': 'N/A',
	Othello: 'Othello',
	Peche: 'Fishing',
	Plateforme: 'Platform',
	'Plateforme / Fighter Scrolling': 'Platform / Fighter Scrolling',
	'Plateforme / Run & Jump': 'Platform / Run & Jump',
	'Plateforme / Run & Jump Scrolling': 'Platform / Run & Jump Scrolling',
	'Plateforme / Run Jump Scrolling': 'Platform / Run & Jump Scrolling',
	'Plateforme / Shooter Scrolling': 'Platform / Shooter Scrolling',
	'Puzzle-Game': 'Puzzle',
	'Puzzle-Game / Egaler': 'Puzzle / Equalize',
	'Puzzle-Game / Glisser': 'Puzzle / Glide',
	'Puzzle-Game / Lancer': 'Puzzle / Throw',
	'Puzzle-Game / Tomber': 'Puzzle / Fall',
	Quiz: 'Quiz',
	'Quiz / Allemand': 'Quiz / German',
	'Quiz / Anglais': 'Quiz / English',
	'Quiz / Coréen': 'Quiz / Korean',
	'Quiz / Espagnol': 'Quiz / Spanish',
	'Quiz / Français': 'Quiz / French',
	'Quiz / Italien': 'Quiz / Italian',
	'Quiz / Japonais': 'Quiz / Japanese',
	'Quiz / Musical Anglais': 'Quiz / Music English',
	'Quiz / Musical Japonais': 'Quiz / Music Japanese',
	Réflexion: 'Thinking',
	Renju: 'Renju',
	Rythme: 'Rhythm',
	"Shoot'em Up": "Shoot'em Up",
	"Shoot'em up / Diagonal": "Shoot'em Up / Diagonal",
	"Shoot'em up / Horizontal": "Shoot'em Up / Horizontal",
	"Shoot'em up / Vertical": "Shoot'em Up / Vertical",
	'Shooter Small': 'Small Shooter',
	Shougi: 'Shogi',
	Simulation: 'Simulation',
	'Simulation / Science Fiction': 'Simulation / Science Fiction',
	'Simulation / Véhicules': 'Simulation / Vehicles',
	'Simulation / Vie': 'Simulation / Life',
	Sport: 'Sport',
	'Sport avec animaux': 'Sport / Animals',
	'Sport / Baseball': 'Sport / Baseball',
	'Sport / Basketball': 'Sport / Basketball',
	'Sport / Billard': 'Sport / Billiards',
	'Sport / Bowling': 'Sport / Bowling',
	'Sport / Boxe': 'Sport / Boxing',
	'Sport / Bras de fer': 'Sport / Arm Wrestling',
	'Sport / Combat': 'Sport / Combat',
	'Sport / Course a pied': 'Sport / Running',
	'Sport / Cyclisme': 'Sport / Cycling',
	'Sport / Dodgeball': 'Sport / Dodgeball',
	'Sport / Extrême': 'Sport / Extreme',
	'Sport / Fitness': 'Sport / Fitness',
	'Sport / Flechette': 'Sport / Darts',
	'Sport / Football': 'Sport / Soccer',
	'Sport / Football Américain': 'Sport / American Football',
	'Sport / Golf': 'Sport / Golf',
	'Sport / Handball': 'Sport / Handball',
	'Sport / Hockey': 'Sport / Hockey',
	'Sport / Jeu de palet': 'Sport / Puck Game',
	'Sport / Lutte': 'Sport / Wrestling',
	'Sport / Multisports': 'Sport / Multisports',
	'Sport / Natation': 'Sport / Swimming',
	'Sport / Nautique': 'Sport / Water Sports',
	'Sport / Parachutisme': 'Sport / Skydiving',
	'Sport / Ping pong': 'Sport / Table Tennis',
	'Sport / Rugby': 'Sport / Rugby',
	'Sport / Skateboard': 'Sport / Skateboard',
	'Sport / Ski': 'Sport / Skiing',
	'Sport / Sumo': 'Sport / Sumo',
	'Sport / Tennis': 'Sport / Tennis',
	'Sport / Volleyball': 'Sport / Volleyball',
	Stratégie: 'Strategy',
	Tir: 'Shooting',
	'Tir / 1ere Personne': 'Shooting / First Person',
	'Tir / 3eme Personne': 'Shooting / Third Person',
	'Tir avec accessoire': 'Shooting / With Accessory',
	'Tir / Avion': 'Shooting / Plane',
	'Tir / Horizontal': 'Shooting / Horizontal',
	'Tir / Missile Command Like': 'Shooting / Missile Command Like',
	'Tir / Run and Gun': 'Shooting / Run and Gun',
	'Tir / Space Invaders Like': 'Shooting / Space Invaders Like',
	'Tir / Vehicule': 'Shooting / Vehicle',
	'Tir / Véhicule': 'Shooting / Vehicle',
	'Tir / Vertical': 'Shooting / Vertical',
	'Tir / Vue de dessus': 'Shooting / Top-Down',
	'Versus Fighting': 'Versus Fighting',
	'Versus Fighting Co-op': 'Versus Fighting Co-op',
	Vertical: 'Vertical',
}

export function translateGenre(genre: string, locale: string): string {
	if (locale === 'fr') return genre
	return GENRE_FR_TO_EN[genre] ?? genre
}
